### ISSUE TITLE
Feminism critical blog wrongly blacklisted 

### ISSUE THREAD

**Issue by philnice** [409H/EtherAddressLookup#1025]
A danish blog that in reasonable and rational terms criticises feminism and its political campaigns (like metoo) has been blacklisted as malicious. I had to remove EtherAddressLookup from Google Chrome in order to access it, as I am not versed in changing settings. This is problematic for two reasons: 

1. Political criticism is not malicious. No one is forced to read opinions that they find disagreeable, and even if they do, they are not harmed by doing so. Comfort and safety are two different things. This is misuse of blacklisting in order to censor.  

2. When protection against genuinely malicious content is misused in this way and has to be removed in the interests of open debate, it exposes users to real threats.

Blog: "Kønsdebat. Nyheder, dokumentation og debat om kønspolitik og kønsforskelle":
http://xn--knsdebat-54a.dk/blog/?p=111&fbclid=IwAR2UukhSL2kNqxKRGkXjMajmWmwTEDp8cJMB7omMeLVQKnpWJTXXJIagris

**Comment by 409H** [comment]
Please see https://github.com/409H/EtherAddressLookup/issues/532#issuecomment-387731112
