### ISSUE TITLE
Blockchain-Sachverständiger.de is not a malicious site 

### ISSUE THREAD

**Issue by legal-law** [409H/EtherAddressLookup#1032]
http://xn--blockchain-sachverstndiger-zhc.de is not a malicious site - it is just a brand new registered German punicode domain - not more not less. There`s no reason to blacklist that domain.

**Comment by 409H** [comment]
Hi, by default EAL blacklists punycode domains as they were popular for phishers to use against many domains. You can disable the behaviour here: https://github.com/409H/EtherAddressLookup/wiki/Blacklisted-Domains#punycode-domains

We will be soon implementing local whitelists so you can whitelist whatever. Apologies for the inconvinence
