### ISSUE TITLE
this is Black Mailing for get Money

### ISSUE THREAD

**Issue by m9734** [409H/EtherAddressLookup#1040]
thos black mailing for get money how much money you want to end your back mailing

**Comment by m9734** [comment]
how much money you want because you are black meller

**Comment by 409H** [comment]
I am not black mailing anyone. The domain - I assume is empowr - was blacklisted as they are sending private keys to their backend.

Closing. Duplicate of https://github.com/409H/EtherAddressLookup/issues/1038
