### ISSUE TITLE
Whitelist www.myethershop.co

### ISSUE THREAD

**Issue by uniquarkD** [409H/EtherAddressLookup#109]
Hi, my domain www.myethershop.co is blacklisted for an unknown reason. Please, whitelist the domain. We are on online shop that let you shop from Amazon with ETH. Please,  at least do a Google search before blacklisting a domain.

https://themerkle.com/what-is-myethershop/

**Comment by 409H** [comment]
Hi, apologies, but this was probably caught in the MyEtherWallet levenshtein algorithm (https://repl.it/JZQ5/11) to auto-block similar domains (usually used to phish MEW users).

I will whitelist the domain so it won't be blacklisted anymore. Please give ~15minutes for whitelists to sync
