### ISSUE TITLE
WTF google sites is blacklisted???

### ISSUE THREAD

**Issue by hwengmgr** [409H/EtherAddressLookup#1107]
I tried to go to sites.google.com, which is a normal useful site and got a blocked address as a phishing address. WTF?

**Comment by 409H** [comment]
That domain is not on the blacklist nor has never been on the blacklist. Please can you show me a screenshot?

https://github.com/409H/EtherAddressLookup/search?q=sites.google.com&unscoped_q=sites.google.com

**Comment by alcedo** [comment]
I am facing the same issue. i visited sites.google.com and this is what isee

![image](https://user-images.githubusercontent.com/1174679/69780407-276fa580-11e6-11ea-8b51-03a58315c1ff.png)

**Comment by 409H** [comment]
Thank you for the screenshot. This was blacklisted by a 3rd party, and my implementation uses the hostname. I've whitelisted the hostname so it will not be blacklisted anymore. Whitelisted in https://github.com/409H/EtherAddressLookup/commit/1fdc9df9df376ab909b0b80071a6b2e9b099724f

Please allow ~10minutes for caches to update
