### ISSUE TITLE
black listed ethero.net

### ISSUE THREAD

**Issue by setformore** [409H/EtherAddressLookup#114]
my computer got blacklisted when I tried to signup on 
ethero.net
setformore3@gmail.com

**Comment by 409H** [comment]
Hi, thanks - this was caught on the auto-blacklist of domains similar to myetherwallet. Whitelisting now

**Comment by 409H** [comment]
Which is the legit site? `ethero[dot]co[dot]uk` or `ethero[dot]net`?

**Comment by setformore** [comment]
thank you

**Comment by 409H** [comment]
@setformore getting quite a lot of hits for ethero. Which is the correct domain? There's quite a few. See above.

**Comment by setformore** [comment]
(dot)net
