### ISSUE TITLE
Don't override overflow CSS

### ISSUE THREAD

**Issue by blorange** [409H/EtherAddressLookup#12]
Love the extension!

It does make browsing Etherscan a pain though, check the screenshot:

![image](https://user-images.githubusercontent.com/26729007/27980271-a4607d1e-6331-11e7-882b-43e35b1d70c7.png)

**Comment by 409H** [comment]
Will be coming up on the next release :)

**Comment by 409H** [comment]
Currently testing this - it should be up tonight for manual installation, and published on the Chrome extension store to be automatically updated early morning, depending on how fast Chrome publishes it :)

**Comment by 409H** [comment]
This is downloadable and can be manually installed by [downloading the .zip release](https://github.com/409H/EtherAddressLookup/archive/v1.3.3.zip) and following the instructions on the `README.md` file.

Also pushing to the Chrome extension store, so give it about 10 hours for Chrome to pull the update 😃
