### ISSUE TITLE
Very much I ask you to help !!!

### ISSUE THREAD

**Issue by mciron** [409H/EtherAddressLookup#129]
Hello!
Very much I ask you to help with the resolution of the arisen problem!
I registered on the ICON website and September 20 took part in the pre-sale of coins, transferring 4.98 Ether from the purse 0xC4841948e38d180F77e0292f0137CC866d5F090f  (MyEtherWallet) and received 12450 coins. The wallet is available at: https://www.myetherwallet.com
Literally the next day I went to the hospital, where I lay for a whole month - they discovered oncology. While lying in the hospital I remembered that on September 20, by the evening I decided to check the receipt of coins into the account and saw a message in the Slack (the link on which was located on the ICON website and has now been changed to the Telegram), allegedly from the ICON site, that there were some difficulties with transferring coins and all are asked to come urgently and check their wallets. Next, there was a link to the purse site CORRECT !!! I was frightened and hurried to go to the link by entering a file and password. And only then I saw that the site address is not quite correct: http://myethereumwalletntw.com/
I immediately left this site, but in the hospital remembering about this case and reading on the Internet, I realized that I got on a spy site and entered there a file and a password. And so they now have 99.9% of my file and password from the wallet. Then I found on the Internet that the site was found to be fake and blocked from 27.09.2017. ((((((
myethereumwalletntw.com
 Archive History Share
URL: http://myethereumwalletntw.com/
Category: Phishing - MyEtherWallet
Status: Offline (September 27th, 2017, 19:09:27 UTC)
IP: 5.230.195.199
EtherAddressLookup: Blocked 
Google Safe Browsing: Blocked
Nameservers:
ns200.01isp.com
ns201.01isp.net

I immediately took out the remnants of Ether from my wallet, transferred the remainders from the miner pool and immediately led them to another purse (now on the account of 0,009 Ether), but I can not withdraw the coins yet !!! And now I'm very much afraid that when the coins are unfrozen, I will not have time to dispose of them and they will be stolen!
They have a file and password from the wallet, but only ICON can link the purse address to my login (email) and password. Can there be any way out of this situation, so I do not lose tokens ?? Help and advise please !!!! For me it is very significant money, especially in this health situation.
I will send and photos and documents for ICON (when the process begins - I can send for earlier as an option) - I'll pass the test. What should I do after this? How to secure coins in your wallet and not let them go to scammers?
On the Internet and the answers to the questions I read that everything in the wallet takes place in the client's browser and you can not change the file and password. But if everything happens on my side, then the password entered when creating a purse in some directory is stored on my computer and theoretically I can change it. It is inextricably linked with the file (which can not be changed, as I understand it) and if it is possible to change the password, scammers will not be able to enter. And I can with a secret key. Can there be some kind of robot program that can transfer tokens to another address as soon as they are thawed? Maybe all the same there are at least some options, because I understood everything in time and so far nothing happened ??? !!!
Once again I very much ask for help!
Sincerely, Nikolay Makarov (Russia, Nizhny Novgorod)   --   mciron@yandex.ru

**Comment by 409H** [comment]
Hi, I would set up a watcher with a geth node and execute a `transfer()` call for the token when you can transfer the tokens.

Usually, the attackers we come across are there to empty the wallet as much as they can and then move on to the next victim, they'll haven't (from what I've seen) set up watchers to transfer tokens in the future.

Your 0.009 ETH will be fine for gas, keep that in the wallet.

**Comment by mciron** [comment]
Good afternoon!
Unfortunately I do not speak English well and can only communicate through a Google translator. In addition, I'm not a great specialist in computers and crypto currency. Mining started studying recently and this is my first participation in the ICO.
I did not quite understand what I can do to protect frozen tokens in my wallet. If this does not make it very difficult for you, could you write me a step-by-step instruction for further action (detailed and simple language-for the child))))))).
Thanks in advance! And thank you very much for responding!

**Comment by mciron** [comment]
Good afternoon!
Unfortunately I do not speak English well and can only communicate through
a Google translator. In addition, I'm not a great specialist in computers
and crypto currency. Mining started studying recently and this is my first
participation in the ICO.
I did not quite understand what I can do to protect frozen tokens in my
wallet. If this does not make it very difficult for you, could you write me
a step-by-step instruction for further action (detailed and simple
language-for the child))))))).
Thanks in advance! And thank you very much for responding!

2017-10-19 22:38 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Hi @mciron, please join the MyEtherWallet Slack channel and DM me (409H) where I can assist you better in real-time

**Comment by mciron** [comment]
Hello!
Please explain how I can join DM me (409H) for real-time help, or better give a link to go.
Slack after that incident with a phishing site I do not want to use anymore.
Thanks in advance!

**Comment by 409H** [comment]
Sure, join the Slack team here: https://myetherwallet.herokuapp.com/ and message me directly `@409H` (may have slow reply times for about 8 hours whilst I'm at work), alternatively chat in `#support` and someone else may be able to help you before I can.

**Comment by mciron** [comment]
https://myetherwallet.herokuapp.com/   --- Failed! invite_limit_reached

What should be done??? Tell me please!

**Comment by tayvano** [comment]
@409H Our slack invites are shut down. ☹ ☹ ☹

**Comment by mciron** [comment]
https://myetherwallet.herokuapp.com/ --- Failed! invite_limit_reached

What should be done??? Tell me please!

2017-10-23 11:27 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
> Our slack invites are shut down. ☹ ☹ ☹

@tayvano :cry: oh

@mciron - I'll set up a tlk.io when I've finished work and invite you there and we can go through setting up a watcher - if our timezones don't match, I'll publish the steps on my site anyways

**Comment by mciron** [comment]
I live in Russia. Below are the time zones for this. I went to:
https://tlk.io/409h Need I have something else to do to see your
recommendations in real time?Thank you!!!
With respect,
Nikolai.

2017-10-23 12:49 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Hi @mciron - please come to the room here to chat: https://tlk.io/285f53

**Comment by mciron** [comment]
Hello! I went to the link https://tlk.io/285f53 you specified, but
apparently I'm doing something wrong. ((((
Either I stopped at the wrong time. Can you specify the time that is
convenient for you? I'll take care of you ...
Thank you!

2017-10-23 23:26 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Around 1900 BST (around 8 hours time)

**Comment by mciron** [comment]
BST - British Summer Time --- Around 7:00 PM? Do I understand correctly?
Thank you!

2017-10-24 13:07 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Yeah, that's correct

**Comment by mciron** [comment]
Hello! Yesterday, unfortunately, I had to go on a business trip on an
emergency. Only returned. Maybe you can do it today? The same as previously
said: BST - British Summer Time --- Around 7:00 PM
Thank you!

2017-10-24 14:09 GMT+03:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Hi @mciron - yes, 1900 BST works for me tonight :)

**Comment by mciron** [comment]
Hello! I went to the link https://tlk.io/285f53 you specified

2017-10-25 16:26 GMT+03:00 H <notifications@github.com>:

**Comment by mciron** [comment]
Hello!

I found in my wallet mew (where there are only unfrozen ICON tokens and the
balance 0,009 ether) transaction 0 ether which I did not do

https://etherscan.io/address/0xC4841948e38d180F77e0292f0137CC866d5F090f

Please tell me what this can mean and what to do about it?

Many thanks!

2017-10-25 16:26 GMT+03:00 H <notifications@github.com>:

**Comment by mciron** [comment]
Hello!
I found in my wallet mew (where there are only unfrozen ICON tokens and the balance 0,009 ether) transaction 0 ether which I did not do
https://etherscan.io/address/0xC4841948e38d180F77e0292f0137CC866d5F090f
Please tell me what this can mean and what to do about it?
Many thanks!

**Comment by 409H** [comment]
Please open a new issue if you are still having problems.
