### ISSUE TITLE
Add to blacklist ASAP

### ISSUE THREAD

**Issue by RamiKalunov** [409H/EtherAddressLookup#131]
https://raiden.online
https://stormtoken.cc
Add to blacklist

**Comment by 409H** [comment]
Thanks for the report - blacklisted

https://github.com/409H/EtherAddressLookup/commit/66becf807bced0f0b7266ae2c52099a8f31019d8#diff-7d2c56a4f7ef38903da8c53848c4efd6

https://github.com/409H/EtherAddressLookup/commit/3336d0882b189451d9f1d6e036b3de6f221db196
