### ISSUE TITLE
Zero Width Character Attack Vector

### ISSUE THREAD

**Issue by Samyoul** [409H/EtherAddressLookup#136]
### The Problem

There seems to be a new way of phishing on the Ethereum network. After reading this article there may be a need to address the issue of scammers stealing ether by giving fake .`eth` addresses.

https://medium.com/@enslisting.com/dealing-with-ens-names-beware-of-this-phishing-attack-6936f6b8b9e4

---
### Proposed Solution

Add a new function for detecting .eth ENS addresses, and another for detecting zero width character in the eth ENS address. Something like :

```javascript
//Finds ENS addresses
getENSAddresses()
{
	var arrWhitelistedTags = new Array("code", "span", "p", "td", "li", "em", "i", "b", "strong", "small");
	var strRegex = /(^|\s|:|-)(\S+(?:\.eth))(?:\s|$)/gi;
	var output = [];

	//Get the whitelisted nodes
	for(var i=0; i<arrWhitelistedTags.length; i++) {
		var objNodes = document.getElementsByTagName(arrWhitelistedTags[i]);
		//Loop through the whitelisted content
		for(var x=0; x<objNodes.length; x++) {
			var strContent = objNodes[x].innerHTML;
			
			//Look for ENS address patterns
			if( strRegex.exec(strContent) !== null) {
				
				var ENSAddresses = getMatches(strContent, strRegex);
				//Check is any of the ENS matches have ZWCs
				for(var y=0; y<ENSAddresses.length; y++){
					if(hasZeroWidthCharacters(ENSAddresses[y])){
						// Code to warn the user that they may be getting phished
					}
					else{
						// Code to replace ENS address with a link
					}
				}

			}
		}
	}
}

//Detect Zero Width Characters
hasZeroWidthCharacters(input)
{
	var startLength = input.length;
	var zeroWidthChars = "\u200B|\u200C|\u200D|\uFEFF|\u2028|\u2029";
	var re = new RegExp(zeroWidthChars);

	var result = input.replace(re, '');

	return (startLength > result.length);
}

//Get RegEx matches
function getMatches(string, regex, index) {
	index || (index = 0); // default to the 0th capturing group
	var matches = [];
	var match;
	while (match = regex.exec(string)) {
		matches.push(match[index]);
	}
	return matches;
}
```

This change should probably be made to the https://github.com/409H/EtherAddressLookup/blob/master/js/DomManipulator.js JS.

---

I think the important thing to do is to warn the user that the address is potentially dodgy, it may not be, but using ZWCs in your .eth address is a good sign you are trying to pretend to be someone you are not. Perhaps ENS will address this with the next version release, but until then the vulnerability will be there.

Do you agree with this approach? If so I'll code the rest of the functionality and open a pull request.

**Comment by 409H** [comment]
Hi Samyoul, thanks for the issue! 

Actually EAL doesn't do anything with `.eth` domains _yet_, so there is no functionality to modify to add logic for ZWC's. Although, please open a PR with this and if you have the time, a `.eth` resolver/lookup (EAL is intended to be a block explorer as an extension, so this would suit really good!)

If you don't have the time to do a `.eth` lookup, no problem, I'll keep this issue open until we have something in the works and we can use your code (giving you credits) :smile:

**Comment by Samyoul** [comment]
Ok, perhaps we can split this issue up into two parts.

`.eth` domain lookup and then ZWC detection. I'll open a `.eth` lookup and then in a separate pull sort the ZWC warning.

**Comment by 409H** [comment]
Awesome, thanks!
