### ISSUE TITLE
ENS .eth domain lookup

### ISSUE THREAD

**Issue by Samyoul** [409H/EtherAddressLookup#137]
Following on from issue #136 we need to implement an ENS domain lookup in the same fashion as standard Ethereum address lookup works.

**Comment by Samyoul** [comment]
@409H Question, is a dedicated ENS lookup needed for this app? The following urls will give valid results.

https://etherscan.io/address/mewtopia.eth
https://etherscan.io/address/0x7cb57b5a97eabe94205c07890be4c1ad31e486a8

https://etherchain.org/account/mewtopia.eth
https://etherchain.org/account/0x7cb57b5a97eabe94205c07890be4c1ad31e486a8

The logic that currently gives the user a block explorer link is:

```javascript
objNodes[x].innerHTML = strContent.replace(
	new RegExp(strRegex, "gi"),
	'$1<a title="See this address on the blockchain explorer" ' +
	'href="' + this.strBlockchainExplorer + '/$2" ' +
	'class="ext-etheraddresslookup-link" ' +
	'target="'+ (objBlockchainExplorer.hostname === window.location.hostname ? '_self' : '_blank') +'">$2</a>'
);
```

Looking at this there are no checks that the link points to a valid address, so I'm presuming that is not a prerequisite.

**Comment by 409H** [comment]
Ah, sorry, I think I've misunderstood you earlier.

When I said a ENS lookup, I meant some sort of screen that does something similar to what Etherscan does, see below;

![image](https://user-images.githubusercontent.com/2313704/31906729-c0f8225e-b829-11e7-9de8-dbb086ecb7bb.png)

I think you're saying something along the lines of adding a link to a block explorer (like Etherscan) for strings like `mewtopia.eth`?

**Comment by Samyoul** [comment]
Ah, ok, I see. I think I misunderstood you.

>I think you're saying something along the lines of adding a link to a block explorer (like Etherscan) for strings like mewtopia.eth?

Yes, this is what I'm suggesting, because at the moment the application converts ethereum addresses into links to a selected block explorer.

In order to create this kind of functionality for EAL the application would need access to an Ethereum node, or better a server that has parsed the block data from the Ethereum blockchain.

What about a transitional set of functionalities that reference pre-existing block explorers, and then move onto developing the block analysis server to pass data to the client?

**Comment by 409H** [comment]
> What about a transitional set of functionalities that reference pre-existing block explorers, and then move onto developing the block analysis server to pass data to the client?

Sounds good for phase 1! 👍

**Comment by Samyoul** [comment]
Looking at a lot of the enhancements they seem to be dependent on having programmatic access to a blockexplorer.

I think that building a new explorer may be overkill, at the moment any way, when we can use APIs https://etherscan.io/apis.

I'd suggest that we develop a whole new extension to this application, a server side portion that is called by the client extension.

Benefits:

- We don't expose our API key.
- We can control API calls, and cache and return results as needed.
- We build the beginnings of a service that gives the user client side info about an account on the page they are looking at. (which I think is the aim of this project)

I propose that we'll need a new repo for managing this functionality as none of it will be related to the functionality in this repo, except for the calls requesting data.

**Comment by Samyoul** [comment]
Dependent issues (at least from my understanding):

- https://github.com/409H/EtherAddressLookup/issues/3
- https://github.com/409H/EtherAddressLookup/issues/143

**Comment by 409H** [comment]
I agree with the above. I'll review the 2 PRs that are open and get them packaged tonight, then I'll hit you up to chat more about this.

I'm at work right now, so will be in about 10 hours.

**Comment by 3esmit** [comment]
Awesome!
