### ISSUE TITLE
Conflict with MEW Contract manager

### ISSUE THREAD

**Issue by Samyoul** [409H/EtherAddressLookup#138]
With EAL active a user is not able to select from the existing contract list.

![myetherwallet com](https://user-images.githubusercontent.com/5702426/31914685-8cb16360-b843-11e7-8286-0ebf6719d83c.png)

With EAL deactivated MEW works as expected.

![myetherwallet com 1](https://user-images.githubusercontent.com/5702426/31914687-8d8371d4-b843-11e7-83fa-329ec1c2da31.png)
![myetherwallet com 2](https://user-images.githubusercontent.com/5702426/31914688-8e749c94-b843-11e7-9942-c8be2a404933.png)

@409H Are you able to replicate this?

**Comment by 409H** [comment]
@Samyoul Good find - yep, I can replicate

I think the POA should be to not do the address logic for EAL if an `li` has an attribute `ng-repeat`. What do you think?

**Comment by Samyoul** [comment]
The current structure with EAL is:

```html
<ul class="dropdown-menu dropdown-menu-left" ng-show="dropdownExistingContracts">
   <!-- ngRepeat: abi in ajaxReq.abiList track by $index -->
	<li ng-repeat="abi in ajaxReq.abiList track by $index" class="ng-scope">
		<a ng-click="selectExistingAbi($index)" class="ng-binding">300 - Warrior for Battle Contract 
			<small class="mono ng-binding">
				<a
				title="See this address on the blockchain explorer"
				href="https://etherscan.io/address/0xaEc98A708810414878c3BCDF46Aad31dEd4a4557"
				class="ext-etheraddresslookup-link ext-etheraddresslookup-link-highlight"
				target="_blank"
				>0xaEc98A708810414878c3BCDF46Aad31dEd4a4557</a>
			</small>
		</a>
	</li>
	...
</ul>
```

**Comment by Samyoul** [comment]
I think that the bug is related to the application JS firing before Angular can do its thing, because manually altering the HTML doesn't give this issue.

I think your idea handles this bug as gracefully as possible.

Is it possible to defer the execution of the application JS until after the page JS has finished?

**Comment by 409H** [comment]
> Is it possible to defer the execution of the application JS until after the page JS has finished?

Yep, should be able to modify this block in DomManipulator

```
window.addEventListener("load", function() {
    let objEtherAddressLookup = new EtherAddressLookup();
});
```

**Comment by 409H** [comment]
Will be looking at this tonight 1900 (GMT timezone)
