### ISSUE TITLE
Identicons break layout in Etherscan.io

### ISSUE THREAD

**Issue by christoph2806** [409H/EtherAddressLookup#162]
EAL inserts identicons before recognized addresses. This looks nice, but unfortunately it breaks the layout in Etherscan.io
![image](https://user-images.githubusercontent.com/431015/32580592-47f2a720-c4e6-11e7-8cd1-6a5607c649ab.png)

**Comment by tayvano** [comment]
Adding

```
.address-tag {
    white-space: nowrap;
}
```

should solve it

**Comment by Samyoul** [comment]
I'll look into it and push a fix

**Comment by Samyoul** [comment]
Yeah, @tayvano that does the trick. I'll apply the fix to the inserted `<a>` element as we have direct control over that.

**Comment by 409H** [comment]
@christoph2806 - pushing to Chrome dev store now - you should see it automatically update within an hour or so. If you manually installed, please download [the latest release](https://github.com/409H/EtherAddressLookup/releases/tag/v1.11)
