### ISSUE TITLE
Levenshtein distance on MEW

### ISSUE THREAD

**Issue by 409H** [409H/EtherAddressLookup#17]
Implement a Levenshtein distance algorithm to detect similar hostnames to that of myetherwallet.com. 

https://en.wikipedia.org/wiki/Levenshtein_distance

This should help detect against `myet.herwallet.com` and `myeth.erwallet.com` type of impersonations.

**To discuss**
- An acceptable edit distance
- If there is >= _x_ edit distance, should we disable interaction with the domain or just show a warning?

cc: @tayvano

**Comment by 409H** [comment]
@sogoiii what's your twitter? I'd like to add your handle when I tweet about the update, if I may

**Comment by sogoiii** [comment]
sure, my twitter handle is @angellopozo i'm the co-founder @hellosugoi as well :)

**Comment by 409H** [comment]
Awesome - will mention both (or 1 depending on char limit) as soon as I've gone over the release again and published to the store 😺

**Comment by sogoiii** [comment]
yea no prob. Ill retweet it as well.
