### ISSUE TITLE
Why is my IP blocked?

### ISSUE THREAD

**Issue by coolcash4live** [409H/EtherAddressLookup#187]
I was trying to login into my MEW account but it is not working. Kindly help me disable the security. Thanks

**Comment by 409H** [comment]
Hi @coolcash4live  - can you confirm the domain that is blocked (a screenshot would be helpful) - Thanks

**Comment by 409H** [comment]
Closing the issue as it has gone stale. 
Please open a new issue with more information if you are still having a problem.
