### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by 409H** [409H/EtherAddressLookup#20]
Modify the view to have trusted bookmarks to various sites (myetherwallet, etherscan, ethplorer, etherchain, r/ethereum, r/ethtrader). These should be icons that you can click on. 

I discovered loads of people on reddit and twitter were using links or manually typing (and if there was a link, they'd click it) to go to MyEtherWallet, which caused the phishing campaigns to be really effective. If the extension has an icon straight to MyEtherWallet, hopefully it helps them use that instead of relying on a link from someone.

The circles being the sites favicon

![image](https://user-images.githubusercontent.com/2313704/28060494-2d82bd06-661f-11e7-9912-0935a8b9a2b4.png)

Please vote in the below poll by clicking the option (**POLL ENDED**):
![image](https://user-images.githubusercontent.com/2313704/28241106-af2ee528-6985-11e7-96ca-6f72b17d0146.png)

I'll aggregate the poll results on July 14, 2017. Depending on the result, it will be implemented or not. If the results favour "impartial", then I'll leave the feature out but keep an open discussion on GitHub.

Hopefully this will help users by using bookmarks instead of links.

**Comment by oscalation** [comment]
This is the most cited suggestion on social media to prevent malicious social engineering attacks. Use bookmarks. This feature is a great idea.

**Comment by 409H** [comment]
Seems like [gh-polls](https://github.com/tj/gh-polls) isn't serving the poll anymore.

Votes when I last looked stood at;

5 YES
2 NO
5 IMPARTIAL

**Comment by 409H** [comment]
Poll ended.

![image](https://user-images.githubusercontent.com/2313704/28241096-9238b1a6-6985-11e7-915b-9cffacc72556.png)

**Comment by 409H** [comment]
https://github.com/409H/EtherAddressLookup/releases/tag/v1.6
