### ISSUE TITLE
coverwallet site 

### ISSUE THREAD

**Issue by tomcorbin** [409H/EtherAddressLookup#201]
When trying to the following site is being blocked.

https://harrydenley.com/EtherAddressLookup/phishing.html#https://my.coverwallet.com/quote

https://harrydenley.com/EtherAddressLookup/phishing.html#https://my.coverwallet.com/notifications

coverwallet provides insurance services for small business and I need to interact with this site.

**Comment by 409H** [comment]
Hi, please allow ~10minutes for caches to update and it should now be whitelisted :)
