### ISSUE TITLE
Incorporating the blacklist in a derivative work - hosts files

### ISSUE THREAD

**Issue by StevenBlack** [409H/EtherAddressLookup#203]
Hi Harry @409H,

I love your [blacklist](https://github.com/409H/EtherAddressLookup/blob/master/blacklists/domains.json), especially its active curation.  Good work on that, keep up the good fight.

I'd like to include the blacklist as a source in [my amalgamated hosts repo](https://github.com/StevenBlack/hosts/blob/master/readme.md).  This repo offers a base amalgamated hosts file that can be augmented with additional hosts for porn, gambling, fake news, etc.  I would include your blacklist in the base hosts file, so therefore in all the other hosts files as well.

I see your [MIT License statement](https://github.com/409H/EtherAddressLookup/blob/master/LICENSE) and I thank you for that.

Have you considered publishing the blacklist in hosts file format?  If so, I could periodically source it directly.  Otherwise I'm happy to augment my generator to pre-process your `domains.json` data as part of the process that builds the various flavours of hosts files we offer.

Thanks for everything you do!

**Comment by 409H** [comment]
Thanks @StevenBlack :)

I've not even thought about writing a tool to convert it into a hosts file format. 
Feel free to adjust your generator though 👍 

Thanks for reaching out

**Comment by StevenBlack** [comment]
Hi Harry @409H I notice domains listed with path elements in the blacklist.

[Lines 2534-2536 in the blacklist](https://github.com/409H/EtherAddressLookup/blob/master/blacklists/domains.json#L2534), which lists `twitter.com/OmiseG0` and others, for example.

Bug?

**Comment by 409H** [comment]
@StevenBlack Yep, that shouldn't be there.

Although, we will be in the future, accompanying domains with paths. Would it be easier for you if we put them in another blacklist?

**Comment by StevenBlack** [comment]
Harry @409H I plan to sanitize lists for protocols, paths, ports, and things so no problem, either way.

In this case, `twitter.com` would have landed in the general hosts file.  So likely I'll just reject domains with adornments.

Thanks for maintaining your blacklist!

**Comment by 409H** [comment]
Awesome - let me know if you run into any difficulties or have any more questions :+1: 

No problem, thanks for consuming them in your project.
