### ISSUE TITLE
Add report link feature

### ISSUE THREAD

**Issue by dylandamsma** [409H/EtherAddressLookup#21]
It's unclear to me how I can report a link. Now, I know I could technically do a pull request and all that, but I would have to figure out how to do that first -- let alone other beginners/non-devs.

Is it possible to add a report feature to the tool for malicious URLs? I'd be happy to function as reviewer.

**Comment by 409H** [comment]
Ah, very good idea. 
I've not really thought about this.

Perhaps a link to a new issue in the repo, and the extension pre-fills the input? As of now, we are getting domains submitted via Slack and Twitter.

**Comment by 409H** [comment]
To add on to previous reply, I've just updated the [README.md](https://github.com/409H/EtherAddressLookup#blacklisted-domains) to help with contributing to the blacklist. I will add a quick link to the extension.

**Comment by 409H** [comment]
Live with v1.5 https://github.com/409H/EtherAddressLookup/releases/tag/v1.5

**Comment by sogoiii** [comment]
nice
