### ISSUE TITLE
Whitelisted site blocked

### ISSUE THREAD

**Issue by myetheroll** [409H/EtherAddressLookup#212]
Hey,

I was just made aware by one of your users that myetheroll.com is blocked and tagged as 'phishing' despite already being on the whitelist (https://www.reddit.com/r/etheroll/comments/7jdwax/etheraddresslookup_extension_blocking/).

Cheers!

**Comment by 409H** [comment]
Hi @myetheroll - I'll investigate this, thanks for the report. 
Which page is it redirecting you to? I am able to browse it without being redirected. 

Are you able to attach a screenshot?

**Comment by myetheroll** [comment]
Thanks for having a look at this!

I'm not the one experiencing the problems, so not sure.
Might be a case of outdated code.

**Comment by 409H** [comment]
Merging issue into https://github.com/409H/EtherAddressLookup/issues/262
