### ISSUE TITLE
wrong address marked as phishing

### ISSUE THREAD

**Issue by sourabhsriom** [409H/EtherAddressLookup#215]
I have bookmarked the link for myetherwallet : https://www.myetherwallet.com ad this is what I am using. I am not sure why this was marked. Please take a look.

**Comment by rivetgeek** [comment]
I am also having this issue. Is there a legitimate reason for blacklisting myetherwallet?

**Comment by 409H** [comment]
Hi @sourabhsriom @rivetgeek  - There was a race condition bug in v1.13 for EAL. I published v1.13.1 as soon as reports came in (I was unable to replicate the bug)

You should be running v1.13.1 which solves the issue. IF you're still having issues, please open a new issue. Thank you!
