### ISSUE TITLE
The 'warning' page doesn't load consistently.

### ISSUE THREAD

**Issue by dylandamsma** [409H/EtherAddressLookup#22]
I've tried 10 malicious urls listed in the blacklist database and often had the 'warning screen' not trigger and was able to navigate the fake website freely. As I'm not technical, not sure what could cause this, however you may want to look into it.

**Comment by 409H** [comment]
Thanks - looking into it now

**Comment by 409H** [comment]
What domains were you able to browse?

**Comment by dylandamsma** [comment]
myetherwaillet.com - was one of them, the warning page did not fire, until a few refreshes. It seems to mainly happen on the first visit when you installed the chrome extension only a few minutes ago, but was able to reproduce a second time for the site. Only on the third time loading the page it warned me. (there were about 20min between installing extension and visiting site)

**Comment by 409H** [comment]
Thanks for the info - will have a fix out shortly as soon as I can reproduce it

**Comment by dylandamsma** [comment]
Try creating a new person in chrome, install the extension on that new chrome profile, enable it, turn on the blacklist, wait for a bit while browser is open and then in a new tab navigate to that address. -- This will emulate a new user.

P.s. I'm sending some new imagery your way you can use for the chrome extension screenshots on the chrome store and will add this to our safety guide for beginners on cryptominded.com

**Comment by 409H** [comment]
Fixed in v1.3.5
