### ISSUE TITLE
Linked to main-net, while browsing in test-net etherscan

### ISSUE THREAD

**Issue by derblub** [409H/EtherAddressLookup#225]
When inspecting tx on the test-net, linked addresses don't take the current test-net into account.

Example: 
https://rinkeby.etherscan.io/address/0x3af10461B77fbe5dC6c1138A6faC86D397e1580D

**Comment by 409H** [comment]
Hi @derblub - thanks for the report.

I'll get a feature out this week (before Friday) to fix this

**Comment by 409H** [comment]
Hi @derblub - v1.13.2 is now being published in the Chrome store. You should get the update shortly.

If you manually installed it, download the extension here: https://github.com/409H/EtherAddressLookup/releases/tag/v1.13.2

**Comment by derblub** [comment]
Awesome @409H! Thanks for this fast fix!
