### ISSUE TITLE
Unblock https://myetherscan.io/

### ISSUE THREAD

**Issue by MioGreen** [409H/EtherAddressLookup#227]
Hi guys,

Thank you for an amazing plugin. We like it very much in our team. 

Could you please unblock our project? We are not a phishing, we are working with Chinese audience, and improve our project every day. Internally we are working on some collectible (like kitties) analytics and want to be supplement service for myetherwallet and bring the best analytics for Asia market. 

Mike

**Comment by 409H** [comment]
@MioGreen is there a reason behind you using the branding of popular site etherscan.io?

![image](https://user-images.githubusercontent.com/2313704/34150062-29150f04-e49f-11e7-964e-47a1e08c6162.png)

![image](https://user-images.githubusercontent.com/2313704/34150068-2f087d42-e49f-11e7-8667-6a90b40a22b8.png)

**Comment by tayvano** [comment]
I think we should get Matt's opinion on this too

**Comment by MioGreen** [comment]
On my opinion, it was mistake of a previous dev team, who tried to play on etherscan.io popularity. Personally I dislike it and we have run project redesign, which will be available soon. For now I will hide our current logo from the site. Will it be enough for now to unblock us to proof that we don't want to play unfair any more?

**Comment by wchuan11** [comment]
Till to-date, the logo and and the overall website is mimicking Etherscan.io unlike what is mentioned that there will be a project redesign.

**Comment by MioGreen** [comment]
Guys, sorry for the delay in an update. The project owner prohibited to change the design. I am closing the issue.
