### ISSUE TITLE
Potential Attack Vector

### ISSUE THREAD

**Issue by abueide** [409H/EtherAddressLookup#234]
My eth got drained into this wallet: https://etherscan.io/address/0x795df9a9699b399ffc512732d2c797c781c22bc7

About 24 hours ago. My wallet is encrypted, and the last time I used it was over 2 days ago. I had this extension installed at the time. I'm documenting this warning that this extension could possibly have been the cause in an effort to find the source of this attack if other people may have been affected here as well.

**Comment by 409H** [comment]
Can you do a history check?

**Comment by abueide** [comment]
@409H https://addons.mozilla.org/en-US/firefox/user/EtherAddressLookup/

Yup definitely looks like I visited that domain. Thats odd though because I installed the plugin such a long time ago. Oh well thanks for your help.

**Comment by 409H** [comment]
Yeah, IIRC they updated the extension to v1.12.1 a couple days ago which had the private key stealer in it. Once it was found by a user and commented on the extension page, they rolled the extension back, then we got it delisted.

I didn't managed to get v1.12.1 of that extension so I couldn't inspect it to see what exactly it was doing.

Announcement here: https://twitter.com/myetherwallet/status/941259882367401984

**Comment by 409H** [comment]
(I've added the `invalid` tag to this issue as it's due to the malicious Firefox extension)

I'll leave the issue open for a couple days in case you need to discuss some more.
