### ISSUE TITLE
Please rename the class "note" to avoid overwriting website styles

### ISSUE THREAD

**Issue by freimuth82** [409H/EtherAddressLookup#251]
https://github.com/409H/EtherAddressLookup/blob/c736a9026497daaecc880ec61b0665ed0b012b8a/css/app.css#L39

We've just came across this style class because the extension injects a stylesheet with this class, which causes overwriting styles used by other websites, which use the class "note" too.

**Comment by 409H** [comment]
Hi @freimuth82 - apologies for the style conflicts, and good catch! I'll release an update tonight after work
