### ISSUE TITLE
VeChain Foundation

### ISSUE THREAD

**Issue by rstube** [409H/EtherAddressLookup#260]
Hi Team

Since today the VeChain foundation page gets blacklisted, site should be legit:

https://vechainfoundation.com/en/

Thank you

**Comment by 409H** [comment]
Hi there!

All the official resources I've read only point to vechain.com - are you able to point me to an official post pointing to vechainfoundation?

**Comment by rstube** [comment]
Hi, 

i´ve received this one:

https://harrydenley.com/EtherAddressLookup/phishing.html#https://vechainfoundation.com/en/

also attached a screenshot:

![2018-01-19_20h12_56](https://user-images.githubusercontent.com/35609656/35167339-6690cd9a-fd55-11e7-9be5-42fefa1604ec.png)

**Comment by 409H** [comment]
The legit domain is https://vechain.com

Where did you come across vechainfoundation.com?

**Comment by rstube** [comment]
This is a cross reference on the legit site, please see the screenshot:

![image](https://user-images.githubusercontent.com/35609656/35171836-73689dc6-fd65-11e7-9b03-578e11d68ca0.png)

It brings you to the page with the roadmap, team and so one, added another screenshot took from MS Edge (no EAL or MetaMask):

![2018-01-19_22h10_23](https://user-images.githubusercontent.com/35609656/35171900-b12d9e04-fd65-11e7-85c9-12264ea8982d.png)

**Comment by 409H** [comment]
Hi, I'm seeing differently. When I go to https://vechain.com (the domain on their twitter account) and go to VeChain Foundation, I'm taken to https://tokensale.vechain.com/en/

**Comment by rstube** [comment]
Hi, this is indeed strange, I will check it from my office on monday and let you know, thanks!

**Comment by 409H** [comment]
Weird. On my laptop I get the vechainfoundation.com link - on mobile I'm getting the tokensale.vechain.com link
