### ISSUE TITLE
ether zero

### ISSUE THREAD

**Issue by ceejandtatiana** [409H/EtherAddressLookup#261]
etherzero.org is coming up as an phishing site by metacert...please help

**Comment by 409H** [comment]
At time of blacklist, the project set off a couple scam flags I look for. Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/668 and https://github.com/MetaMask/eth-phishing-detect/issues/653

**Comment by 409H** [comment]
(I have no power of metacert blacklisting/whitelisting by the way)
