### ISSUE TITLE
ethex.market shouldn't be blacklisted

### ISSUE THREAD

**Issue by danielwalton** [409H/EtherAddressLookup#262]
There is no reason to black list this site. We are a legitimate DApp.

Thanks,
Dan

**Comment by 409H** [comment]
Hi @danielwalton - this domain isn't in the blacklist, so perhaps it's caught in the Levenshtien edit distance. I'll add it to the whitelist.

**Comment by danielwalton** [comment]
Ah, thanks for the quick response!

Can you help me understand what up with Levenshtien edit distance?

Thanks again

**Comment by 409H** [comment]
No problem!

Sure - https://en.wikipedia.org/wiki/Levenshtein_distance

So with an edit distance of 2 with "Hello" as your word, the following will be true

```
Heppo
Hemmo
Hills
Hmmlo
```

But the following won't be true because it has more than 2 characters different

```
Hrkki
Foobar
Goodbye
```

See https://www.youtube.com/watch?v=oIsPB2pqq_8

**Comment by danielwalton** [comment]
Hi Thanks for this.

we are still seeing that our domain might be blacklisted.

"We have detected this domain to have malicious intent and have prevented you from interacting with it.

This is because you have enabled 'Warn of blacklisted domains' setting on EtherAddressLookup Browser Extension. You can turn this setting off to interact with the domain but it's advised not to."

Please help. Thanks,
Dan

**Comment by 409H** [comment]
@danielwalton Is it consistent behaviour or only sometimes? I cannot replicate

**Comment by danielwalton** [comment]
It's not consistent. One out of 10 visits triggers the issue. Please take a look. Just go to the site 10 times, try force refresh too.

Thank you for your attention.

**Comment by 409H** [comment]
I've found the cause of the bug - seems like an issue when you load the page when the whitelist needs refreshing. Will have an update out shortly to fix this.

**Comment by 409H** [comment]
@danielwalton @febrez @myetheroll  - a fix will be published tonight (~2200 GMT).

**Comment by danielwalton** [comment]
thanks!
dan
