### ISSUE TITLE
False Positive on blacklist - mysherpa.be

### ISSUE THREAD

**Issue by nickde9999** [409H/EtherAddressLookup#266]
Hi, mysherpa.be is a tutoring site. No stealing going on, as far as i can tell

**Comment by 409H** [comment]
https://urlscan.io/result/fbebe300-ad10-4c0f-a294-6e81582fd3ac#summary

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.

I believe it was blacklisted due to a positive edit distance.
