### ISSUE TITLE
yelp.com is on the blacklist

### ISSUE THREAD

**Issue by michaelshum123** [409H/EtherAddressLookup#287]
Plz I just want to look at pizza 

https://www.yelp.com/biz/paulys-pizza-joint-san-diego-3?frvs=True&osq=food

**Comment by 409H** [comment]
Hi, what version of EAL do you have? This was fixed in a hotfix v1.14.3

**Comment by michaelshum123** [comment]
oh okay, i'm on 1.14.2! i'll update
