### ISSUE TITLE
ВНИМАНИЕ Мы обнаружили, что этот домен имеет злонамеренные намерения и препятствует вам взаимодействовать с ним.

### ISSUE THREAD

**Issue by Timurmalik** [409H/EtherAddressLookup#288]
Я считаю, что этот домен неправильно внесен в черный список, пожалуйста, 
![screenshot_175](https://user-images.githubusercontent.com/22558291/36058052-61c9c80e-0e42-11e8-995c-0c2e1d9f0d90.png)

**Comment by 409H** [comment]
Which domain?

**Comment by 409H** [comment]
Please open a new issue if your problem persists.
