### ISSUE TITLE
Highlight Matches option is highlighting on Etherscan itself

### ISSUE THREAD

**Issue by jet86** [409H/EtherAddressLookup#35]
When "Highlight Matches" is enabled and "Preferred Blockchain Explorer" is set to "Etherscan.io" Ethereum addresses on Etherscan itself are highlighted, and clicking opens the link in a new tab/window. It would make more sense that when on Etherscan itself the addresses should not be highlighted but instead use Etherscans own linking (which doesn't open a new tab/window).

I have only tested this for Etherscan.io but suspect it may be similar for the other options in "Preferred Blockchain Explorer" as well.

**Comment by 409H** [comment]
I don't think toggling the highlight option to effectively be off if you're on etherscan should be normal behaviour, but open to a discussion with that.

I like the idea of not opening a new tab/window for addresses matched on the Etherscan tab, and instead follow their current link system though.

**Comment by jet86** [comment]
On reflection I agree - highlighting is not an issue (and keeping it consistent makes sense), but yes not opening a new tab/window when on Etherscan would improve usability.

**Comment by 409H** [comment]
@jet86 - sorry for the delay, this will be published tonight. If you installed via chrome webstore, expect an automatic update shortly, otherwise please reinstall manually tomorrow.
