### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by CryptoManiac** [409H/EtherAddressLookup#369]
Hello. 

Recently got a report that my site (https://etherdig.net) is recognized as a phishing resource.

![11111 jpg ebb174ce20c2c18f13d40beee345ae23](https://user-images.githubusercontent.com/1429531/37529103-4d4deed0-2947-11e8-8058-f38fe17f88f2.jpg)

But it's definitely not. Please, correct this issue ASAP.

**Comment by 409H** [comment]
Interesting - I cannot replicate - I will whitelist the domain though
