### ISSUE TITLE
this guys stole eth from people - eths.vu/

### ISSUE THREAD

**Issue by ederwils** [409H/EtherAddressLookup#383]
they use @durov chat account on twiter and created a similar one from Durov and took people eth, saying Durov was making a giveaway eth..

**Comment by 409H** [comment]
Where was the giveaway linked? Which domain?

**Comment by ederwils** [comment]
hi,

here is the site:

https://eths.vu/

check this twiter post:

https://twitter.com/durov
post from march 20th

2018-03-23 0:37 GMT+00:00 H <notifications@github.com>:

**Comment by 409H** [comment]
https://urlscan.io/result/6664561e-2d37-4c4a-ad79-9f88002ea1d9/#summary

**Comment by 409H** [comment]
Thanks for the report - blacklisted in https://github.com/409H/EtherAddressLookup/commit/7f0edf94fe87c0af3f743e224c49e25a4334713c

**Comment by ederwils** [comment]
yes that's it!

what can be done?

2018-03-23 16:18 GMT+00:00 H <notifications@github.com>:
