### ISSUE TITLE
Unable to open Gramnetwork.org

### ISSUE THREAD

**Issue by 3LSupremo88** [409H/EtherAddressLookup#401]
We have detected this domain to have malicious intent and have prevented you from interacting with it.

Good day!

I just like to ask. Why is it I can't access gramnetwork.org? It says"We have detected this domain to have malicious intent and have prevented you from interacting with it."

How am I able to get through it?
[EAL Warning.pdf](https://github.com/409H/EtherAddressLookup/files/1846421/EAL.Warning.pdf)

**Comment by 409H** [comment]
Gramnetwork.org is a phishing/scam site for a Telegram public crowdsale.

There has not been an official announced public sale of Telegram yet.
