### ISSUE TITLE
etherdelta.gitlhub.io = another etherdelta phishing clone

### ISSUE THREAD

**Issue by bidfish** [409H/EtherAddressLookup#43]
etherdelta.gitlhub.io

**Comment by 409H** [comment]
Thank you!

**Comment by 409H** [comment]
https://github.com/409H/EtherAddressLookup/commit/e767f99e45be1c79f2ae59fefd52bdaa692bb56b

**Comment by bidfish** [comment]
Might be helpful using regex and blocking phishing prone domains like *.glthub.io completely ;)

**Comment by 409H** [comment]
Yep, will look at putting some Levenshtein logic into it, like sogoiii did https://github.com/409H/EtherAddressLookup/pull/27 for myetherwallet :smile:
