### ISSUE TITLE
Magnet link problem

### ISSUE THREAD

**Issue by kotchuprik** [409H/EtherAddressLookup#49]
Hey, just found an unpleasant bug — EtherAddressLookup highlights torrent magnet link as Ether address. You could check [here](https://www.ghacks.net/2010/06/05/what-is-a-magnet-link-and-how-does-it-differ-from-torrents/).

![image](https://user-images.githubusercontent.com/802946/28748063-4925fb04-74b6-11e7-9067-80b8afbccad2.png)

**Comment by 409H** [comment]
@kotchuprik  - I will address this issue and get it live this week!

**Comment by 409H** [comment]
@kotchuprik Apologies - I have been really busy. Will push an update tonight. Chrome will auto-update your version, unless you have manually installed, then reinstall tomorrow.
