### ISSUE TITLE
Blocking character look-alikes (ie: myethervallet.com)

### ISSUE THREAD

**Issue by bidfish** [409H/EtherAddressLookup#52]
Blocking all sites where *rn* replaces *m*,  *vv* replaces *w* and *v* replaces *w* might be prudent ;)

**Comment by 409H** [comment]
It could give a lot of false positives, plus we have Levenshtien edit distance on domain myetherwallet.com that @sogoiii implemented in v1.3.7 that will catch them.

I forgot to mention that MetaMask (who are the only other people using the blacklist) now implement the Levenshtien distance https://github.com/MetaMask/metamask-extension/pull/1837 so it shouldn't be a problem not listing all `rn` = `m`, `vv` = `w`, `v` = `w` variants of a domain name as they'll be caught.

You can confirm with the test script here: https://repl.it/JZQ5/6 (a response of `true` will mean it's blacklisted)

**Comment by 409H** [comment]
Pretty much covered with the Levenshtein logic that @sogoiii did.
