### ISSUE TITLE
Scam Address

### ISSUE THREAD

**Issue by zilions** [409H/EtherAddressLookup#55]
Hey Harry,

As discussed, here is some more info about the scamming address, who is impersonating our ICO.

Here are a list of the fake sites:
iconexus.tk
iconexus.ml
iconexus.ga
iconexus.cf

If you require any information about our ICO (real address, real domain, etc), please do not hesitate to ask me.

Thanks.

**Comment by tayvano** [comment]
Probably a good bet to add legit things to whitelist and known malicious urls to blacklist. Have you set up dnstwist or anything to keep an eye on these guys as they spin up new urls?

**Comment by 409H** [comment]
Hi @zilions - can you give more information about your ICO (plus real domain). Also note you can report domains here: https://etherscamdb.info/report/

**Comment by zilions** [comment]
@409H - Our real domain is https://ico.nexus.social/

We've reported a few more imposter domains via the link you provided. Thanks.

**Comment by 409H** [comment]
Thanks @zilions - PR merged just now, relaying the blacklist edits to MetaMask now.
