### ISSUE TITLE
EtherBTC.io blacklisted as a phishing site is error

### ISSUE THREAD

**Issue by joezys** [409H/EtherAddressLookup#56]
For some reason,  http://etherbtc.io, a website providing time sensitive information about the EtherBTC (ETHB) initial coin offering, is listed as a "known phishing site."  It is not a phishing site at all.  The only information we are requesting when someone is registering for our ICO is their name, email address, and their "wallet address," AKA their "account address," starting with 0x, which we need in order to send them free ETHB for registering and setting up their MyEtherWallet.

We'd greatly appreciate it if  you would remove http://etherbtc.io from your blacklist and instead, add it to your whitelist so anyone running metamask is not  scared away from registering for our ICO which takes place in 9 days.  Thank you for promptly making this change.

**Comment by tayvano** [comment]
Please add it to the whitelist via PR. This is a community maintained project. You are part of the community.

**Comment by tayvano** [comment]
Closed via #59

**Comment by evilbuon** [comment]
toi nhan duoc 1 ETHB, va toi khong biet lam gi voi no, no khong co gia tri tren thi truong
