### ISSUE TITLE
Remove domain ethereal.capital from blacklist

### ISSUE THREAD

**Issue by kristofferjon** [409H/EtherAddressLookup#57]
My company's domain ethereal.capital is coming up as being on your blacklist but should not be.

Please remove it ASAP.

Regards,
Kristoffer Sheather
Ethereal Capital

**Comment by tayvano** [comment]
Please add it to the whitelist via PR. This is a community maintained project. You are part of the community.

Youve not been blacklisted btw; you got caught in levenstein distance.
