### ISSUE TITLE
please remove ethermine.org from blacklist

### ISSUE THREAD

**Issue by probag17** [409H/EtherAddressLookup#58]
ethermine.org is giving me the metamask blacklist error page - just started happening 20 minutes ago.... what's the deal?  I can't check my mining dashboard anymore.  

ethermine.org is a legit website, has it been hacked or something?

**Comment by clarky07** [comment]
I'm also seeing this. Anyone know what's going on?

**Comment by sogoiii** [comment]
Hmm.. I see it in one browser but not the other. Both have metamask.

**Comment by tayvano** [comment]
Anyone is free to open a pull request adding domain to whitelist or blacklist. In this case, it is likely something got caught in the levelshtein distance reading.

**Comment by probag17** [comment]
I'm not very technical, so I have no idea how it happened or why - all I know is that one moment I was checking my miner dashboard and the next refresh it was blacklisted.

Hopefully one of you smart people can help fix this! :)

**Comment by tayvano** [comment]
I'm.on mobile at the moment. If you navigate to the whitelist json file, click the pencil in upper right if that file, and then add 'thedomain.url', to the top (just try to match what is there-itll be pretty obvious I think).

Scroll to bottom. In form message box: Add some details about why you are adding to whitelist and click the green button... twice until it says 'pr submitted'

If you screw it up, it's okay bc myself or Harry have to check it before its live. Don't be scared! 😊

**Comment by probag17** [comment]
Taylor,

I proposed the change you requested, and I found some additional details about the problem.  It only happens if you type ethermine.org and not www.ethermine.org.  Somehow not adding the "www." results in a blacklist error.

Let me know how else I can help, thank you!

**Comment by probag17** [comment]
ethermine.org is still getting blocked by metamask, yet www.ethermine.org is not.  Has the whitelist been pushed yet?

**Comment by sogoiii** [comment]
I suggest going over to [eth-phishing-detect](https://github.com/MetaMask/eth-phishing-detect) and making a pull request. Metamask is using that module now.

**Comment by 409H** [comment]
@probag17 - Just waiting on this to be accepted: https://github.com/MetaMask/eth-phishing-detect/pull/4
