### ISSUE TITLE
domain 'm.famalk.net' is not blacklist

### ISSUE THREAD

**Issue by kysee** [409H/EtherAddressLookup#61]
I am owner of m.famtalk.net domain.
I'm software developer and have been providing the Famtalk service (another name is MoMo).
The Famtalk service is a SNS service for users to generate meetings, share it via another SNS and check attendants.

Why is this domain added to blacklist ???

**Comment by jdheeter** [comment]
There is an algorithm that is used to blacklist sites that are not manually blacklisted, I found a false positive today as well. Maybe the algorithm needs to be tweaked. To override, the site needs to be added to the whitelist.

**Comment by tayvano** [comment]
Plz add to whitelist for now. Will merge until at computer to adjust levenstein setting

**Comment by kysee** [comment]
please add to whitelist and...

**Comment by kysee** [comment]
could i know the algorithm that is used to check blacklist sites.

**Comment by kysee** [comment]
i want to study just and ...
i want to know why is my domain added to blacklist...
how can i get some document for your algorithm...???

**Comment by sogoiii** [comment]
its levenshtein. I added it to this repo a while ago. I think something is odd with metamask blacklisting.

**Comment by 409H** [comment]
You can check the algorithm here: https://repl.it/JZQ5/3
