### ISSUE TITLE
Ethermine.org

### ISSUE THREAD

**Issue by monko760** [409H/EtherAddressLookup#63]
Are we to believe this large pool is malicious? PLEASE tell me this is an error and they will be whitelisted from now on. Ready to switch pools ASAP if sufficient evidence is produced that I should not be mining with them.

Thank you
Robert

**Comment by plewis00** [comment]
I was about to highlight this as an issue as well (I joined to do this) - Metamask wouldn't let me visit the site this morning. I can't find anything else on the internet about it, so I assume it's a mistake of some sort. All my earned Ether has always been sent to my wallet promptly.

**Comment by mirzap** [comment]
I don't see Ethermine in a blacklist file. Don't know why metamask reports it as a phishing site. Didn't find any report that ethermine has done any malicious activities.

**Comment by plewis00** [comment]
There was another thread I saw too, if you add 'www' to the front of the address it's fine, but just 'https://ethermine.org...' it doesn't like. I can still access the site without shutting off MetaMask, shares still being submitted and dashboard updated too. I think it's a mistake but would like to know what caused it or if there is any real cause for concern.

**Comment by 409H** [comment]
Hi, It's probably a false positive with the Levenshtien algorithm. MetaMask have their own version now: https://github.com/MetaMask/metamask-extension/pull/1837

Tayvano has pushed the domain to the whitelist so there won't be a false positive with EAL chrome extension. If you still have issues using MetaMask, reach out to them. We are working with them to make detection better and false-positives become less.
