### ISSUE TITLE
this is Pishing site scam!!

### ISSUE THREAD

**Issue by jinyungyou** [409H/EtherAddressLookup#639]
Flash is launching a new blockchain that will foster  the creation and transfer of coins based on an open source cryptographic protocol, without being managed by any central authority (decentralization). The Flash project is aimed at increasing the rate at which public adaptation of the blockchain technology will happen by making transaction speed faster and also being an alternative means of payment.

We aim at making transactions all over the world easier, faster and transparent. This project has been in its development stage for over a year and we believe it is time to introduce this unique project into the main stream.

A private sale will be conducted to individual investors who show interest in the project.

The total FLASH tokens to be distributed during the lightening-drop stands at 200,000,000 which Is 50% of the total supply of the FLASH tokens created.

We will list on the first exchange when tokens are fully distributed to members who signed up for the airdrop or participated in the ICO.
The tokens will be locked until distribution has ended. 

Due to the massive interest shown by the community to the Flash Project we have put in place some rules and regulations to govern the lightening-drop registration process.

- [x] Multiple registration will lead to instant disqualification.
- [x] We will review all airdrop registration and disqualify irregular accounts.
- [x] There is no limit on the referral program, your referral link will be automatically sent to your email after registration.
- [x] The lightening-drop will automatically close once the number of tokens  available has been distributed.
- [x] We reserve the right to not accept participants for any reason.

Visit https://flashblocks.io to join the airdrop 
Regards
Flash Team

**Comment by 409H** [comment]
Thanks - blacklisted in https://github.com/409H/EtherAddressLookup/commit/2dfc47b0e24328d5a1a6a70a2c9df21e6a3eeb5a
