### ISSUE TITLE
Phishing on https://ethermine.org/ ???

### ISSUE THREAD

**Issue by botzko** [409H/EtherAddressLookup#64]
Metamask is preventing me from entering my miner pool stats at:
https://ethermine.org/miners/

> MetaMask has detected this domain to have malicious intent and has prevented you from interacting with it.
> 
> This is because the site was listed on the EtherAddressLookup malicious site blacklist.
> 
> You can turn MetaMask off to interact with this site, but it's advised not to. We blacklisted it for a reason.

Is this site **harmfull**?

**Comment by plewis00** [comment]
Add 'www' in front and it's fine, suggests it's safe.

**Comment by botzko** [comment]
Thank you for the fast response. The site is indeed accessible when 'www' is entered.

**Comment by 409H** [comment]
Domain has been whitelisted on EAL chrome extension - if you're still having issues, reach out to MetaMask. We are in contact with them working closely on creating a better blacklist/whitelist to prevent these false-positives.
