### ISSUE TITLE
EOS Registration

### ISSUE THREAD

**Issue by teksavvy74** [409H/EtherAddressLookup#645]
While registering EOS I receive the following message:
Links sent to you unprovoked are often malicious. If you arrived here from a link sent to you via Slack, DM, Twitter, message, or email, it is likely someone trying to trick you so they can steal your crypto. 

Try seeking out a trustworthy, secure link on your own: top Google results (not Google Ads!), Verified Twitter Accounts, or asking someone you know & trust. Once you find the correct URL, bookmark it.

**Comment by 409H** [comment]
Which domain is it?
