### ISSUE TITLE
ethereumdev.kr

### ISSUE THREAD

**Issue by nomadblcok** [409H/EtherAddressLookup#65]
I'm founder of Ethereumdev.kr

I have partnered with the founder of 'ethereumdev.io' to translate the contents of ethereumdev.io to provide services.
For Koreans, translated materials are needed because of language barriers.
Now I have plans to fill in our own content.
It is also not a profitable site.
Why is my website detected as blacklist in metamask?
Take care. 
If you want, I can show the mail with ethereumdev.io.

**Comment by tayvano** [comment]
Please add to whitelist. On mobile but can merge.

Example of how to add https://github.com/409H/EtherAddressLookup/pull/59/files

(Go to file, click pencil icon in top right, add url, click green buttons until done)

**Comment by nomadblcok** [comment]
now, The problem continues.
![image](https://user-images.githubusercontent.com/30717768/28960679-953812d8-793a-11e7-8f7e-425e35431f43.png)

**Comment by nomadblcok** [comment]
How can I ?

**Comment by 409H** [comment]
MetaMask is using the blacklist, but they have different functionality on their side for whitelisting (and auto-blacklisting (ie: Levenshtien)). Open an issue here: https://github.com/MetaMask/metamask-extension/issues/new
