### ISSUE TITLE
Remove everex.cash from blacklist

### ISSUE THREAD

**Issue by alexesnsk** [409H/EtherAddressLookup#66]
Hey Guys,

I wanted to make pull request but didn't find any everex mention there. Therefore metamask shows website https://everex.cash as blacklisted.
It's wrong it's our wallet website (not token sale but remittance application). 

The main website https://everex.io has a link to the wallet. There is a pic: http://take.ms/StLWv

P.s. Thank you for blacklisted everex.online - its real scammers.

**Comment by tayvano** [comment]
Please add to whitelist. On mobile but can merge.

Example of how to add https://github.com/409H/EtherAddressLookup/pull/59/files

(Go to file, click pencil icon in top right, add url, click green buttons until done)
