### ISSUE TITLE
why my domain blocked?

### ISSUE THREAD

**Issue by etherdesignlab** [409H/EtherAddressLookup#71]
ethercard.io blocked for me,
but i dont see him in blacklist

**Comment by MrLuit** [comment]
Only blocked on Metamask for me.

**Comment by ropod7** [comment]
How long does it takes to go away from algo blacklist, if domains are merged in whitelist by hand?

**Comment by 409H** [comment]
@etherdesignlab  - ethercard.io isn't in EAL blacklist nor caught by the LevenAlgo (https://repl.it/JZQ5/8). I'll open communications with MetaMask to see if it's something their side.

@ropod7 If you're using EAL, the blacklist is sync'd every 3 minutes, unsure about MetaMask, they've recently changed their rules.

**Comment by blakemiles** [comment]
ethermine.org is showing up as blacklisted as well, but not on the blacklist.json

**Comment by blakemiles** [comment]
also.. there is no intuitive way of turning off the blacklist redirect within settings

**Comment by 409H** [comment]
@blakemiles are you using EAL or MetaMask? Does the phishing alert page have a red or blue background?

**Comment by Fukunaga42** [comment]
We are blacklisted too https://dether.io ??
The alert page has red background

**Comment by Fukunaga42** [comment]
Our PR https://github.com/409H/EtherAddressLookup/pull/69  doesn't change anything we still are blacklisted

**Comment by 409H** [comment]
@Fukunaga42 This seems to be an issue with MetaMask then. It looks like they've employed some logic 15hours ago (https://github.com/MetaMask/eth-phishing-detect) that seems to be causing a lot of false-positives. If the domain isn't on the blacklist (or caught with the LevenAlgo) they you *should* be good using EAL.

I'm trying to communicate with them now, but I think the timezone difference is causing an issue/they're afk. Please hold with me

**Comment by Fukunaga42** [comment]
@409H Thanks you, I try to contact them too

**Comment by 409H** [comment]
Issue resolved on MetaMask side. Closing issue.
