### ISSUE TITLE
Extension is blocking domain I own

### ISSUE THREAD

**Issue by denifednu** [409H/EtherAddressLookup#715]
Hi, 
I own this domain: http://α1.net  (aka http://xn--1-ylb.net)
I can confirm there is no malicious code or intent on this site.
Please can you consider not blocking it?  When users try to visit it they get this message:
We have detected this domain to have malicious intent and have prevented you from interacting with it.
Thanks

**Comment by 409H** [comment]
Please see https://github.com/409H/EtherAddressLookup/issues/532#issuecomment-387731112

I have issued a whitelist though 👍
