### ISSUE TITLE
Remove fenêt.re from black list please.

### ISSUE THREAD

**Issue by yoannmoinet** [409H/EtherAddressLookup#725]
Hi,
just found out that my address https://fenêt.re was wrongly black listed.
It's a basic webpage to present a Mac OSx application I made.
Could it be white-listed please.

Thank you.

**Comment by hahnmichaelf** [comment]
Hey @yoannmoinet, your website was blocked by a punycode blocker. I've opened a PR for @409h to merge, but until he is able to merge it, you can turn off the punycode blocking switch:

![punycode](https://user-images.githubusercontent.com/29407814/41508892-9f78d6dc-7219-11e8-9024-1245f580ce6f.PNG)

**Comment by yoannmoinet** [comment]
That's cool, I understand.
Thank you very much.
