### ISSUE TITLE
Feature Request: Add the domain you attempted to visit on teal phish-page so I don't have to go trace back to my original message to find it when I forget to incognito before checking a site out :P

### ISSUE THREAD

**Issue by tayvano** [409H/EtherAddressLookup#75]

**Comment by 409H** [comment]
Hey, you talking about http://eal-phishing-stats.herokuapp.com/?

If so, I'm updating that tonight :smile: 
For a domain to be listed, that all depends on Google Analytics reporting, but will check with that and see if I can get near real-time

**Comment by tayvano** [comment]
No sorry. So you know if you click a URL and it's blocked. It would be nice to have the url you were attempting to visit there. Bc I end up going to check a bunch to see if they've been added and then not knowing which open tab is which (and therefore which sites have been blocked)

**Comment by 409H** [comment]
Ahh, right I see.

Will implement this week (hopefully tonight) :+1:
