### ISSUE TITLE
wrongly blacklisted domain

### ISSUE THREAD

**Issue by braskalov** [409H/EtherAddressLookup#777]
синергия.орг is just a simple catalog, nothing to do with malicious software

**Comment by 409H** [comment]
Please see https://github.com/409H/EtherAddressLookup/issues/532#issuecomment-387731112

**Comment by jeajam45** [comment]
Please make prompt action on this issue 'coz I really don't know how to go about it. I'm a bit new with this crypto currency trading and all... I'm at lost and very much confused with what is happening on my page and domain. Why in the world is this kind of activity allowed? Whereas we're just simply performing  tasks to be done daily with our platform - empowr.com. Please advise...
[empowr_whitepaper2018.pdf](https://github.com/409H/EtherAddressLookup/files/2620155/empowr_whitepaper2018.pdf)

**Comment by 409H** [comment]
@jeajam45 please see https://github.com/409H/EtherAddressLookup/issues/1038#issuecomment-442082473
