### ISSUE TITLE
Please blacklist this phishing website [https://myetherwallet-msgg.top]

### ISSUE THREAD

**Issue by valluminarias** [409H/EtherAddressLookup#806]
Hello I just an email with this phishing website, please include it in the blacklist.

[https://myetherwallet-msgg.top]

Big thanks.

**Comment by 409H** [comment]
Thanks - blacklisted in https://github.com/409H/EtherAddressLookup/commit/c873356c76efeb0fc2e4fd05fcbc9d27f0d7a88e
