### ISSUE TITLE
invest

### ISSUE THREAD

**Issue by mehrnazazale** [409H/EtherAddressLookup#813]
Hi team , i purchased 2 ether to spark address to invest ,after i purchase my ether i get warning and i get band from telegram and website , also i didn't receive any email to see how much spark i bought , 
please help

**Comment by 409H** [comment]
Please can you give more information? 

Which telegram group?
Which domain?
Which address did you send ETH to?

**Comment by mehrnazazale** [comment]
sparkster telegram
i went to sparkster official  website send 2 ether
in 0xd0aCAc843AAAb4Cef20b322405405E67e90147d1
i can see the trnsaction in blockchain too.

**Comment by 409H** [comment]
We've flagged the domain and related addresses here: https://etherscamdb.info/address/0xd0acac843aaab4cef20b322405405e67e90147d1

Sorry but nobody can rewind a transaction. Anyone saying they can will scam you

**Comment by mehrnazazale** [comment]
you mean i get scam ?

**Comment by mehrnazazale** [comment]
that is not my falt , i wen to official website , i already been to this
ico for long times , is not right ,.i need my refund

**Comment by 409H** [comment]
Sorry to say but yes, you got scammed. This is not the official domain
