### ISSUE TITLE
is this a phishing list only or political?

### ISSUE THREAD

**Issue by chrcoluk** [409H/EtherAddressLookup#84]
It blocks twitter O_o

www.twitter.com/omise__go
twitter.com/omise__go

Now that url (which is now dead but still in your list) may well not have had savoury content, but I doubt there is actual phishing going on twitters own webspace.  So why is it there?

**Comment by tayvano** [comment]
1) I visit Twitter all the time and have had no issues.

2) The above accounts were spreading malicious / phishing content including but not limited to:

- Fake ICO addresses

- DMS with surverys in return for free ETH

- Fake Airdrop News

- Phishing links to fake OmiseGo website with fake address

- Phishing links to fake MEW website

You'll catch more bees with honey, honey. If you don't like something, open a PR, don't get snarky or underestimate the scope of the phsihing / scams going on right now.

**Comment by 409H** [comment]
>  but I doubt there is actual phishing going on twitters own webspace.

You're mistaken. Creating a Twitter account that is cloning the branding of an official Twitter handle, posting links to a malicious site to grab users private key, is phishing.

> So why is it there?

Because it was phishing users.
