### ISSUE TITLE
malicious site

### ISSUE THREAD

**Issue by divineprofitbiz** [409H/EtherAddressLookup#865]
I had clicked on a link from eosgas token airdrop for KYC completion.

But i keep getting a message that the site is malicious.

Please kindly look into this as i needed to compleye the KYC process in the next 3 days dedline.

Here is the site tagged, malicious:
https://harrydenley.com/EtherAddressLookup/phishing.html#https://www.eosgas.co/kyc/#blacklisted

![eosgas maliciou page kyc](https://user-images.githubusercontent.com/40695846/43318189-c1536496-9197-11e8-8505-ce5edddb745f.GIF)

**Comment by 409H** [comment]
It redirects you to a fake MyEtherWallet designed to steal your funds after phishing your keys. Please do not fall victim.
