### ISSUE TITLE
почивнидни.com

### ISSUE THREAD

**Issue by baltika10** [409H/EtherAddressLookup#872]
[http://почивнидни.com](http://почивнидни.com)
That's just site with vacation days in Bulgaria. Nothing related crypto/eth/finance, but for some reason I receive warning

**Comment by 409H** [comment]
Hi, please see https://github.com/409H/EtherAddressLookup/issues/532#issuecomment-387731112

![https://user-images.githubusercontent.com/2313704/39815987-bfd3cb5e-5391-11e8-90aa-6a6d3d0a9d25.png](https://user-images.githubusercontent.com/2313704/39815987-bfd3cb5e-5391-11e8-90aa-6a6d3d0a9d25.png)

You need to disable "Block all punycode domains"
