### ISSUE TITLE
BaföG page blacklisted

### ISSUE THREAD

**Issue by Liqs-v2** [409H/EtherAddressLookup#885]
[The page for financial aid while studying in Germany is blacklisted](https://www.bafög.de), I doubt that this is a legitimate blacklist.

**Comment by 409H** [comment]
Hey, this is because you have the "Block all punycode domains" option enabled. See https://github.com/409H/EtherAddressLookup/issues/532#issuecomment-387731112

![image](https://user-images.githubusercontent.com/2313704/43601343-d90a1926-9684-11e8-845d-62e9ce56e80f.png)
