### ISSUE TITLE
Please unblock EtherAddressLookup

### ISSUE THREAD

**Issue by joyce31004** [409H/EtherAddressLookup#959]
이 도메인은 모든 punycode 도메인을 차단했기 때문에 차단되었습니다 (기본 동작). 이 도메인에 액세스하려고하는데 안전하다고 확신하는 경우 EtherAddressLookup 설정 의 동작 을 비활성화하십시오 .

This domain is blocked because you have blocked all punycode domains (this is default behaviour). If you want to access this domain and you're sure it's safe, please disable the behaviour in the EtherAddressLookup settings.

Use Nano Leisure Address

**Comment by joyce31004** [comment]
[](url)https://harrydenley.com/EtherAddressLookup/phishing.html#https://sign.xn--mytherwalet-3qb10c.com/sign-message.html#punycode

**Comment by 409H** [comment]
Hello, that is a fake MyEtherWallet designed to steal your keys. Please stay away from that domain.

**Comment by kvhnuke** [comment]
@joyce31004 I can confirm you were saved by EtherAddresaLookup extension. The domain you were about to visit is a malicious MyEtherWallet link that will steal your funds

**Comment by m9734** [comment]
way you Block my Domain my account safe and secure what you want

**Comment by m9734** [comment]
You Block my the www.empower.com way have you power any
