### ISSUE TITLE
Black listed etherdelta.com

### ISSUE THREAD

**Issue by jahigrant** [409H/EtherAddressLookup#96]
https://twitter.com/etherdelta?lang=en&lang=en did you check it out before blacklisting?

**Comment by 409H** [comment]
Yes, and there's more concerns than that. https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by jahigrant** [comment]
I have used etherdelta.com just now, I deposited and withdrew tx https://etherscan.io/address/0x38eed870f8f9036ff75426d66f4501354ccb7d7a

**Comment by 409H** [comment]
The concern isn't primarily with withdrawing, but with giving private keys

**Comment by 409H** [comment]
see https://github.com/MetaMask/eth-phishing-detect/issues/76
