### ISSUE TITLE
Whitelisting of https://earn.dailydivs.com

### ISSUE THREAD

**Issue by CryptoChronologist** [409H/EtherAddressLookup#971]
Hello Admins,

I would like to ask that the domain https://earn.dailydivs.com/ be removed from the blacklist and be whitelisted. The developers have created a unique fun and easy to use DAPP which it appears is currently being targeted as malicious. There have not been any malicious activities that I have experienced or seen on this domain nor any related domains of dailydivs.com.
I am pleading and asking that you please add https://earn.dailydivs.com/ to your whitelisted sites and any other affiliated sites under https://*.dailydivs.com/.

FYI. I am not being paid to give this review nor my ask for the site to be whitelisted. Please feel free to email me for additional information or find me under the dailydivs discord.

Thanks for your time

**Comment by 409H** [comment]
Hi

`earn.dailydivs.com` was blacklisted in https://github.com/409H/EtherAddressLookup/commit/06b625cb526f88af8f01ab4a93c775963722b2d9 - it is a ponzi scheme with an unverified contract. If you haven't been scammed now there is no telling that you wouldn't be scammed in the future.

Ponzi schemes are illegal and unethical.

Anything with guaranteed daily returns/dividens is most likely a scam.

**Comment by CryptoChronologist** [comment]
Hello, earn.dailydivs.com you say is blocked because it's a ponzi scheme with an unverified contract. If verified is what makes or not make it a ponzi scheme then I would suggest you do dome do diligence. Because it appears that you have not actually looked at the program before make an assumption as to what it may or may not be. earn.dailydivs.com does not guarantee any percentage per-day (clear you haven't actually reviewed the program before making assumptions about it) but instead give its investors an opportunity to earn an income off the investments made them by them and others who have invested.
The un-verification of the code by the Dev was unanimously agreed upon by the users of DailyDivs community to prevent Copycats. Three days after Dailydivs was launched there were at least two (2) copycat websites up and running. One looks pretty much identical to Dailydivs and the other with the same underlining codes with a few things slightly modified and some wording changed. So as to prevent this from happening any further we the Dailydivs community asked the Developer "NOT" to verify the codes for the additions to the sites to prevent further "COPYCATS."
So if your reason for calling or claiming that earn.dailydivs.com a ponzi scheme then I would highly recommend that you come and join the DailyDivs Discord group and speak to the Developer directly and not form an opinion based off an assumption.
I am not saying DailyDivs could never be a scam nor am I saying it is not a scam but that decision I don't think is yours to make nor is it mine. Come and join the discord and learn about DailyDivs and what it's all about current instead of making assumptions.

Thank you
