### ISSUE TITLE
https://нож-витязь.рф domain wrongly blacklisted

### ISSUE THREAD

**Issue by elzeon** [409H/EtherAddressLookup#975]
The following domain is wrongly blacklisted:
https://нож-витязь.рф
https://xn----dtbkge0ah0b5f2a.xn--p1ai/
It is a russian knife online store.

**Comment by 409H** [comment]
This is a punycode domain and they are blocked by default (a lot of phishing domains use this to phish users).

To turn it off, read: https://github.com/409H/EtherAddressLookup/wiki/Blacklisted-Domains#punycode-domains

(Soon we will be releasing user whitelists so you can whitelist whatever)
