### ISSUE TITLE
A safe page that is regarded as a dangerous one

### ISSUE THREAD

**Issue by OriaK** [409H/EtherAddressLookup#982]
Hi,

I wanted to report this site <https://www.xn--4dbcyzi5a.com/2014/05/%D7%94%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%94%D7%9E%D7%9C%D7%90-%D7%9C%D7%92%D7%99%D7%93%D7%95%D7%9C-%D7%A4%D7%98%D7%A8%D7%99%D7%95%D7%AA-%D7%A7%D7%A1%D7%9D/>
as safe. It is an Israeli website that deals with Cannabis and magic mushrooms, which makes it seem suspicious but I've been using it for a long time and it is safe.

**Comment by 409H** [comment]
Hi, this is because it's classed as a punycode domain which is blocked by default. See: https://github.com/409H/EtherAddressLookup/wiki/Blacklisted-Domains#punycode-domains

**Comment by OriaK** [comment]
Oh, I understand. Ok, thank you :)
