### ISSUE TITLE
Domain not trying to steal crypto

### ISSUE THREAD

**Issue by gubbar** [409H/EtherAddressLookup#997]
http://www.lægerneamagerbrogade18.dk/ is not trying to steal Crypto. It's my local doctor :)

**Comment by 409H** [comment]
Hi, this is because by default EAL prevents punycode domains due to the amount of phishing domains using those characters. You can disable it by unticking "Block all punycode domains" - https://github.com/409H/EtherAddressLookup/wiki/Blacklisted-Domains#punycode-domains
